### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/xtext/ui/editor/model/IXtextDocument 	at net.sourceforge.plantuml.xcore.XcoreDiagramIntentProvider.getDiagramInfos

### ISSUE THREAD

**Issue by OepenerPlatt** [OepenerPlatt/plantuml#10]
```
java.lang.NoClassDefFoundError: org/eclipse/xtext/ui/editor/model/IXtextDocument
	at net.sourceforge.plantuml.xcore.XcoreDiagramIntentProvider.getDiagramInfos(XcoreDiagramIntentProvider.java:23)
	at net.sourceforge.plantuml.text.AbstractDiagramIntentProvider.getDiagramInfos(AbstractDiagramIntentProvider.java:120)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:516)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:445)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$DiagramTextChangedListener.diagramChanged(AbstractDiagramSourceView.java:352)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$DiagramTextChangedListener.selectionChanged(AbstractDiagramSourceView.java:347)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:266)
```

**Comment by OepenerPlatt** [comment]
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/2303a7a4-b977-441c-be43-3dc777348482)

**Comment by travkin79** [comment]
I prefer specifying the required plug-ins explicitly so that they can be installed if required. I think, you should add the required xtext plug-in to required plug-ins in the dependencies tab.

**Comment by pbrossel** [comment]
> I prefer specifying the required plug-ins explicitly so that they can be installed if required. I think, you should add the required xtext plug-in to required plug-ins in the dependencies tab.

I also prefer the explicit dependency strategy, but tried to follow the way it was defined in this project.
`Imported packages` is not my friend because you never see if you're right until running the code.

Isn't it worth opening an issue in the base repo? I can do that if you agree.
I also wonder why no one else had this problem in the past?

**Comment by travkin79** [comment]
Since I'm currently the only one working on the PlantUML Eclipse plug-in, I don't need a GitHub issue for that. I could just check the dependencies when creating one of the next PlantUML (for Eclipse) releases. But an issue might have the benefit of not forgetting to do so. ;-)
