### ISSUE TITLE
Xcore is missing when testing IDE

### ISSUE THREAD

**Issue by OepenerPlatt** [OepenerPlatt/plantuml#7]
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/82e0bc5d-641b-4a44-aa6b-3d3a4608b4a5)

Target platform already contains xtext . Used for what ? 

![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/7fae0a44-dd5f-4048-bcb1-ff6d2c626150)

**Comment by OepenerPlatt** [comment]
What should be added ?

```
!SESSION 2024-01-23 20:46:45.161 -----------------------------------------------
eclipse.buildId=unknown
java.fullversion=11.0.7+10
JRE 11 Windows 10 amd64-64-Bit Compressed References 20200422_551 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\KWE\Devel\work\plantuml\space/../runtime-plantuml-2022-09 -dev file:C:/KWE/Devel/work/plantuml/space/.metadata/.plugins/org.eclipse.pde.core/PlantUML4e-2022-09/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.xtext.builder.standalone 4 0 2024-01-23 20:46:59.825
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.builder.standalone [265]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.common.types [267]
         Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.common.types 4 0 2024-01-23 20:46:59.839
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.common.types [267]
  Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.common.types.shared 4 0 2024-01-23 20:46:59.844
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.common.types.shared [269]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.common.types [267]
         Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types.ui
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types.ui; bundle-version="2.28.0.v20220829-0502"
       org.eclipse.xtext.common.types.ui [271]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.purexbase 4 0 2024-01-23 20:46:59.853
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.purexbase [279]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase
    -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.xbase [293]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
              org.eclipse.xtext.common.types [267]
                Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.purexbase.ide 4 0 2024-01-23 20:46:59.863
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.purexbase.ide [280]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.purexbase
    -> Bundle-SymbolicName: org.eclipse.xtext.purexbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.purexbase [279]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase
           -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
              org.eclipse.xtext.xbase [293]
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
                     org.eclipse.xtext.common.types [267]
                       Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase.ide
    -> Bundle-SymbolicName: org.eclipse.xtext.xbase.ide; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.xbase.ide [294]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.purexbase.ui 4 0 2024-01-23 20:46:59.872
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.purexbase.ui [281]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase.ui
    -> Bundle-SymbolicName: org.eclipse.xtext.xbase.ui; bundle-version="2.28.0.v20220829-0502"; singleton:="true"
       org.eclipse.xtext.xbase.ui [298]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types.ui
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types.ui; bundle-version="2.28.0.v20220829-0502"
              org.eclipse.xtext.common.types.ui [271]
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
                     org.eclipse.xtext.common.types [267]
                       Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
              org.eclipse.xtext.xbase [293]
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.purexbase.ide; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.xtext.purexbase.ide; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.purexbase.ide [280]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.purexbase
           -> Bundle-SymbolicName: org.eclipse.xtext.purexbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
              org.eclipse.xtext.purexbase [279]
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase
                  -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types
                  -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types.ui
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types.ui; bundle-version="2.28.0.v20220829-0502"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.purexbase; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.xtext.purexbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.xbase 4 0 2024-01-23 20:46:59.881
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.xbase [293]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.common.types [267]
         Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.xbase.ide 4 0 2024-01-23 20:46:59.936
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.xbase.ide [294]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.xbase [293]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
              org.eclipse.xtext.common.types [267]
                Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.xbase.testing 4 0 2024-01-23 20:46:59.942
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.xbase.testing [297]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.xbase [293]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
              org.eclipse.xtext.common.types [267]
                Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.xbase.ui 4 0 2024-01-23 20:46:59.948
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.xbase.ui [298]
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase.ide; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.xtext.xbase.ide; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
       org.eclipse.xtext.xbase.ide [294]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
              org.eclipse.xtext.xbase [293]
                Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
                     org.eclipse.xtext.common.types [267]
                       Unresolved requirement: Require-Bundle: io.github.classgraph; bundle-version="4.8.138"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.xtext.xbase; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types.shared
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types.shared; bundle-version="2.28.0.v20220829-0502"; singleton:="true"
       org.eclipse.xtext.common.types.shared [269]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types.ui
    -> Bundle-SymbolicName: org.eclipse.xtext.common.types.ui; bundle-version="2.28.0.v20220829-0502"
       org.eclipse.xtext.common.types.ui [271]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.28.0.v20220829-0445"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.xtext.xtext.ui.graph 4 0 2024-01-23 20:46:59.965
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.xtext.ui.graph [304]
  Unresolved requirement: Require-Bundle: org.eclipse.draw2d; bundle-version="3.10.100"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

```

**Comment by OepenerPlatt** [comment]
Edit target platform 
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/f8a6eb92-d049-4cd2-b23b-3f3b6a0b2f30)

**Comment by OepenerPlatt** [comment]
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/0b14e6e7-94df-4d0f-8c79-c2ab305f65bb)

What should we use ? 

![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/b398f682-7cbd-45a0-8e1b-59cda964567d)

![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/3cab8f06-c67d-4322-96d8-ccaa2b4d4bd5)

**Comment by travkin79** [comment]
The target platform already contains the xtext SDK, so I think, there's no need to change anything here. See #2 

No, I'm wrong. I think, you have to add the EMF XCore SDK to the target platform as it as already done for xtext.
